services:
  db_sql:
    image: postgres:latest
    container_name: db_sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sql_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/init/init.sql:/docker-entrypoint-initdb.d/init.sql

  db_nosql:
    image: mongo:latest
    container_name: db_nosql
    ports:
      - "27017:27017"
    volumes:
      - ./data/init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
